"""Seed data for a first-run demo experience.

All seed events are pushed through the same normalize -> persist ->
correlate -> build-incident pipeline used for live events, so incidents,
risk scores, and evidence in the seeded data are generated by the real
backend logic - never hand-crafted.
"""
from datetime import datetime, timedelta, timezone

from sqlalchemy.orm import Session

from app.database.session import SessionLocal
from app.models.event import Event
from app.models.incident import Incident
from app.services import normalization, incident_builder

NOW = datetime.now(timezone.utc)


def _ingest(db: Session, raw: dict):
    normalized = normalization.normalize_event(raw)
    event = Event(**normalized)
    db.add(event)
    db.flush()
    incident_builder.process_new_event(db, event)
    db.commit()


def seed(db: Session):
    if db.query(Event).count() > 0:
        return  # already seeded

    base = NOW - timedelta(hours=6)

    # --- Scenario 1: Possible account compromise (alex) ---
    t = base
    _ingest(db, dict(timestamp=t, event_type="LOGIN_FAILED", user="alex", source_ip="185.23.10.4", device_id="DEVICE-42", source="auth-service"))
    _ingest(db, dict(timestamp=t + timedelta(seconds=90), event_type="LOGIN_FAILED", user="alex", source_ip="185.23.10.4", device_id="DEVICE-42", source="auth-service"))
    _ingest(db, dict(timestamp=t + timedelta(seconds=180), event_type="LOGIN_FAILED", user="alex", source_ip="185.23.10.4", device_id="DEVICE-42", source="auth-service"))
    _ingest(db, dict(timestamp=t + timedelta(seconds=280), event_type="LOGIN_SUCCESS", user="alex", source_ip="185.23.10.4", device_id="DEVICE-42", source="auth-service", severity="MEDIUM"))
    _ingest(db, dict(timestamp=t + timedelta(seconds=380), event_type="NEW_DEVICE", user="alex", source_ip="185.23.10.4", device_id="DEVICE-42", source="auth-service", severity="MEDIUM"))
    _ingest(db, dict(timestamp=t + timedelta(seconds=480), event_type="PRIVILEGE_CHANGE", user="alex", source_ip="185.23.10.4", device_id="DEVICE-42", source="iam-service", severity="HIGH", metadata={"new_role": "admin"}))
    _ingest(db, dict(timestamp=t + timedelta(seconds=580), event_type="FILE_ACCESS", user="alex", source_ip="185.23.10.4", device_id="DEVICE-42", source="file-service", severity="HIGH", destination="payroll.xlsx"))

    # --- Scenario 2: Privilege escalation (morgan) ---
    t2 = base + timedelta(hours=1)
    _ingest(db, dict(timestamp=t2, event_type="LOGIN_SUCCESS", user="morgan", source_ip="91.108.6.20", device_id="DEVICE-08", source="auth-service"))
    _ingest(db, dict(timestamp=t2 + timedelta(seconds=120), event_type="PRIVILEGE_CHANGE", user="morgan", source_ip="91.108.6.20", device_id="DEVICE-08", source="iam-service", severity="HIGH", metadata={"new_role": "admin"}))
    _ingest(db, dict(timestamp=t2 + timedelta(seconds=260), event_type="PROCESS_EXECUTION", user="morgan", source_ip="91.108.6.20", device_id="DEVICE-08", source="edr-agent", severity="MEDIUM", metadata={"process": "powershell.exe"}))

    # --- Scenario 3: Sensitive file access + data transfer (priya) ---
    t3 = base + timedelta(hours=2)
    _ingest(db, dict(timestamp=t3, event_type="LOGIN_SUCCESS", user="priya", source_ip="203.0.113.9", device_id="DEVICE-15", source="auth-service"))
    _ingest(db, dict(timestamp=t3 + timedelta(seconds=150), event_type="FILE_ACCESS", user="priya", source_ip="203.0.113.9", device_id="DEVICE-15", source="file-service", severity="HIGH", destination="customer_database.sql"))
    _ingest(db, dict(timestamp=t3 + timedelta(seconds=260), event_type="NETWORK_CONNECTION", user="priya", source_ip="203.0.113.9", device_id="DEVICE-15", source="network-sensor", severity="MEDIUM", destination="198.51.100.77"))
    _ingest(db, dict(timestamp=t3 + timedelta(seconds=340), event_type="DATA_TRANSFER", user="priya", source_ip="203.0.113.9", device_id="DEVICE-15", source="network-sensor", severity="CRITICAL", destination="198.51.100.77"))

    # --- Isolated harmless / low-signal alerts (should NOT correlate into an incident) ---
    _ingest(db, dict(timestamp=base + timedelta(hours=3), event_type="LOGIN_FAILED", user="sam", source_ip="10.0.0.5", device_id="DEVICE-21", source="auth-service", severity="LOW"))
    _ingest(db, dict(timestamp=base + timedelta(hours=3, minutes=40), event_type="LOGOUT", user="jordan", source_ip="10.0.0.9", device_id="DEVICE-33", source="auth-service", severity="LOW"))
    _ingest(db, dict(timestamp=base + timedelta(hours=4), event_type="NETWORK_CONNECTION", user="jordan", source_ip="10.0.0.9", device_id="DEVICE-33", source="network-sensor", severity="LOW", destination="internal-wiki.local"))

    # --- Normal daily activity (multiple users, spread out, non-correlating) ---
    normal_users = [("sam", "10.0.0.5", "DEVICE-21"), ("jordan", "10.0.0.9", "DEVICE-33"), ("morgan", "91.108.6.20", "DEVICE-08")]
    for i, (u, ip, dev) in enumerate(normal_users):
        ts = base + timedelta(hours=4, minutes=20 * (i + 1))
        _ingest(db, dict(timestamp=ts, event_type="LOGIN_SUCCESS", user=u, source_ip=ip, device_id=dev, source="auth-service", severity="LOW"))
        _ingest(db, dict(timestamp=ts + timedelta(minutes=25), event_type="FILE_ACCESS", user=u, source_ip=ip, device_id=dev, source="file-service", severity="LOW", destination="team_wiki.md"))
        _ingest(db, dict(timestamp=ts + timedelta(minutes=50), event_type="LOGOUT", user=u, source_ip=ip, device_id=dev, source="auth-service", severity="LOW"))

    # --- A resolved false positive incident (new device that was legitimate) ---
    t4 = base + timedelta(hours=5)
    _ingest(db, dict(timestamp=t4, event_type="LOGIN_SUCCESS", user="sam", source_ip="41.72.3.18", device_id="DEVICE-99", source="auth-service", severity="LOW"))
    _ingest(db, dict(timestamp=t4 + timedelta(seconds=60), event_type="NEW_DEVICE", user="sam", source_ip="41.72.3.18", device_id="DEVICE-99", source="auth-service", severity="MEDIUM"))
    db.commit()

    # Mark that last incident (new device) as resolved / false positive as a realistic seed state.
    fp_incident = (
        db.query(Incident)
        .join(Event, Event.incident_id == Incident.id)
        .filter(Event.device_id == "DEVICE-99")
        .first()
    )
    if fp_incident:
        fp_incident.status = "FALSE_POSITIVE"
        db.commit()

    # Mark the privilege escalation incident as under investigation for variety.
    pe_incident = (
        db.query(Incident)
        .join(Event, Event.incident_id == Incident.id)
        .filter(Event.device_id == "DEVICE-08")
        .first()
    )
    if pe_incident:
        pe_incident.status = "INVESTIGATING"
        db.commit()


def run():
    db = SessionLocal()
    try:
        seed(db)
    finally:
        db.close()


if __name__ == "__main__":
    run()
